spring:
  application:
    name: JOB-Details
  data:
    mongodb:
      uri: mongodb+srv://srikanth:srikanth@cluster0.vggqgya.mongodb.net/?retryWrites=true&w=majority
      database: JobDetailsDB
      auto-index-creation: true

server:
  port: 8082




